tasks:
  - command: gp open README.md
  - command: export PATH="/workspace/Example-Cryptol:$PATH"
  - command: cryptol
    
vscode:
  extensions:
    # Add PDF viewing support to VSCode
    - tomoki1207.pdf
    - jldodds.cryptol
